Portfolio setup mobile first pull request
tamoorsaeed22/Portfolio-setup-mobile-firtst pull request #1
Opened 2023-01-17 13:17 UTC by tamoorsaeed22

Summary 
1:Used flex for the session.
2:Used microverse template 1 for reference.
3:FIGMA design has been used to make this portfolio as per requirement.
4:Linting tool that helps improve the site's accessibility, speed, cross-browser compatibility, and more by checking your code for best practices and common errors.
5:Followed GitHub flow.
6:Create branches with different base branches
7:In this project, I have set up a portfolio. My goal was to use all of the tools and practices.

2023-01-17 15:50 UTC, osamaashraf6 requested changes
Hi @tamoorsaeed22 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Good commit messages.
- [x] Descriptive READme file in a professional way.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow
- [x] Nice design.




## Required Changes ♻️

- [ ] kindly👇💯 check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-17 15:50 UTC, osamaashraf6 commented on index.html
> +        I'm Tamoor<br>
- [ ] Great job and have a nice design 😃, but I see that the content of the home section wants to go up a little to be like the design the margin between the header and the content bigger than the Figma Design, so kindly 😊 try to fix the margin between them to be like the Figma design and the design will be attractive for the visitors 👌

> Check the table below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212940609-39177441-b430-4520-b532-c67ff5282d62.png)  |    ![image](https://user-images.githubusercontent.com/83360636/212940710-4f3c689b-5f5e-457f-b43f-3419272a39db.png)|

2023-01-17 15:50 UTC, osamaashraf6 commented on index.html
> +<a href="#" class="link">LET'S CONNECT</a>
- [ ] I see 😃 that you put a big value on the margin between elements, so kindly try to fix that and use the correct margin to be like the Figma Design👌

> Check the table below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|    ![image](https://user-images.githubusercontent.com/83360636/212941825-1d1a5108-fcf1-45d3-b0a8-ae42a0983ace.png)  |    ![image](https://user-images.githubusercontent.com/83360636/212942017-ad22d4c7-476e-4be8-8782-950a7fcd1abe.png)|

2023-01-17 15:50 UTC, osamaashraf6 commented on index.html
> +        I'm Tamoor<br>
- [ ] I see that the type of the font family is not like the Figma so, Kindly 😃try to use the correct font family to be like the Figma Design 💯

> Check the table below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/212944261-11abd5be-a910-48d8-b197-c7932a88024a.png) |   ![image](https://user-images.githubusercontent.com/83360636/212944367-7878a00a-baf1-41f3-8ec6-57e2ddb3f07e.png) |

2023-01-18 10:20 UTC, tamoorsaeed22 commented
1: content bigger than the Figma Design has been resolved.
2:Margin between Header and text has been resolved.
3:font family has been changed according to Figma design .

2023-01-18 10:42 UTC, Ibizugbe approved these changes
Hi @tamoorsaeed22 👋, 

![BigTvGIF (2)](https://user-images.githubusercontent.com/64643995/213150848-5b6923f5-b03e-4c6a-bcb9-6a38c308eb6c.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅
- github flow has been used👍
- linters are passing.👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 10:52 UTC, merged